### ISSUE TITLE
URL not defined?

### ISSUE THREAD

**Issue by Prkns** [leolabs/gatsby-source-spotify#10]
Following through the instructions on installing and configuring this plugin, I've done everything (clientId, clientSecret, Redirect URI) but as soon as I run the `npx` command, I get this error?

```
npx: installed 109 in 6.574s
Starting HTTP server to receive OAuth data from Spotify...
I will open a browser window for you. Please log in using your Spotify credentials.
URL is not defined
```

No browser window opens, and it just hangs there until I cancel it... Any ideas?

**Comment by leolabs** [comment]
I think this could be related to the Node.js version you're using. Could you tell me which version of Node you're using so I can try to reproduce the problem on my machine?

**Comment by Prkns** [comment]
I was running an early version of node 10 but based on what you said, upgraded to v10.18.0 and it seems to have fixed my issue.

Thanks for the advice 👍 

However running the `npx` install script now throw's this error:

```
FetchError: request to https://mosaic.scdn.co/640/63247752eeb4cea940306c45e664e364c8763eb0ab6761  6d0000b2730a6681162da174d75599b377ab67616d0000b27336087dd92791ec7e2d992881ab67616d0000b273a04553  426795f8fb1bb542ad failed, reason: getaddrinfo ENOTFOUND mosaic.scdn.co mosaic.scdn.co:443
```

**Comment by leolabs** [comment]
Hmm, that sounds like a network error either on Spotify‘s or on your side. Could you try it again? :)

**Comment by leolabs** [comment]
I'll close this issue as it hasn't been active kn quite some time. Let me know if the issues still persist.
