### ISSUE TITLE
Cookie SameSite issue

### ISSUE THREAD

**Issue by gibdr7** [leolabs/gatsby-source-spotify#12]
A cookie associated with a cross-site resource at https://spotify.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by leolabs** [comment]
Hey, this sounds more like a browser issue. Could you link an example where this error occurs? :)
