### ISSUE TITLE
RecentTracks refreshing

### ISSUE THREAD

**Issue by nzmitch** [leolabs/gatsby-source-spotify#19]
when it comes to publishing a site with this plugin how would I go about refreshing the recently played tracks? is this possible?

**Comment by leolabs** [comment]
If you want to have real-time data, then it'll be easier to build your own API endpoint that you can call from the browser when your site has loaded. What I do to get kind-of real-time data is to automatically build and deploy my site every night at 3 am with this Gatsby plugin :)
