### ISSUE TITLE
NPM install and Gatbsy version warning

### ISSUE THREAD

**Issue by waylonrobert** [leolabs/gatsby-source-spotify#33]
Awesome work on this! I'm running a newer version of Gatsby, and got this error while trying to npm install:

```
warn Plugin gatsby-source-spotify is not compatible with your gatsby version 3.5.0 - It requires
gatsby@^2.10.8
```
I was able to get it to install by using the `--force` flag, but wanted to log this here in case it's something that needs fixing.

**Comment by leolabs** [comment]
Thanks for the report! I haven't worked on this plugin in a while, but will update it to make it work with Gatsby v3 :)

**Comment by waylonrobert** [comment]
Also saw this during a build earlier today, may be related:

```
warn Calling "touchNode" with an object containing the nodeId is deprecated. Please pass the node
directly to the function: touchNode(node) "touchNode" was called by gatsby-source-spotify
```

**Comment by leolabs** [comment]
I've updated the plugin to support Gatsby v4 :)
