### ISSUE TITLE
Weird issue when restarting gatsby develop

### ISSUE THREAD

**Issue by waylonrobert** [leolabs/gatsby-source-spotify#34]
I made a config change in gatsby-config.js after adding a different plugin, and now I can't get this plugin to work. Attached are screenshots I'm getting. Additionally, it's no longer appearing in GraphiQL. I tried removing the new plugin I added in case there was some kind of conflict, but the problem remains. Any thoughts on how to resolve @leolabs? 

<img width="1148" alt="Screen Shot 2021-06-18 at 4 20 35 PM" src="https://user-images.githubusercontent.com/1198295/122623582-88bdca80-d051-11eb-97e4-b9f592879ce5.png">
<img width="1148" alt="Screen Shot 2021-06-18 at 4 20 59 PM" src="https://user-images.githubusercontent.com/1198295/122623584-8bb8bb00-d051-11eb-98f7-3727a44a5277.png">
<img width="1552" alt="Screen Shot 2021-06-18 at 4 24 29 PM" src="https://user-images.githubusercontent.com/1198295/122623618-b276f180-d051-11eb-841c-bf2486f8d749.png">

**Comment by waylonrobert** [comment]
Sorry for false alarm, this was on my side. My firewall was blocking some outgoing connections. I accepted those and it's working now.

**Comment by leolabs** [comment]
Thanks for the report anyway. That's good info for anyone else who might run into the same issue :)

Sometimes – 1 out of 40 builds or so – I get similar issues as well. It seems that sometimes the API is a bit flakey, but it has improved a lot in the past year.
