### ISSUE TITLE
Illegal Scopes

### ISSUE THREAD

**Issue by josh91hickman** [leolabs/gatsby-source-spotify#5]
I'm getting an "Illegal Scope" response from the oauth endpoint flow when using the command line token generator - it seems these scopes may be illegal? 

```&scope=user-top-read+user-read-recently-played```

**Comment by josh91hickman** [comment]
could be related: https://github.com/spotify/web-api/issues/1262

**Comment by leolabs** [comment]
I've tried it on my end but couldn't reproduce it. Maybe Spotify fixed the issue on their end in the meantime. Could you try it again and report back if it worked for you? :)

**Comment by benstuart1** [comment]
I'm getting the same error, user-top-read is the problem

**Comment by leolabs** [comment]
Hmm, that's weird. I could take that scope out of the oauth request but then I guess you won't be able to access your most played tracks.

**Comment by benstuart1** [comment]
Actually, I fixed it by deleting my app on the Spotify dev dashboard and making a new one.

**Comment by leolabs** [comment]
I've added that workaround to the readme and marked this issue as fixed for now. It seems to be a problem on Spotify's side, but feel free to reopen it, if necessary :)
