### ISSUE TITLE
Feature Request: Configure 'limit' query parameter in gatsby-config.js

### ISSUE THREAD

**Issue by justinsunho** [leolabs/gatsby-source-spotify#9]
Based on [this](https://developer.spotify.com/documentation/web-api/reference/personalization/get-users-top-artists-and-tracks/), `limit` is another query parameter. 20 is nice! but I would love to have (in my case) more.

**Request:** Have the `limit` parameter configurable in `gatsby-config.js`, similar to how `time_range` is a config

Might work on this if I have time down the line.

**Comment by leolabs** [comment]
Hey, thanks for pointing this out! :)

I think I deliberately limited the amount of results to 20 to reduce the risk of running against rate limits. However, this may have changed, so I'll take another look.
